---
abstract: 'Load JSON-encoded data from a server using a GET HTTP request'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Importer-getJSON
provides:
  Catmandu::Fix::get_json:
    file: lib/Catmandu/Fix/get_json.pm
    version: 0.40
  Catmandu::Importer::getJSON:
    file: lib/Catmandu/Importer/getJSON.pm
    version: 0.40
requires:
  Catmandu: 0.9
  Furl: 3.0
  Moo: 1.0
  URI::Template: 0.18
  perl: v5.10.1
resources:
  bugtracker: https://github.com/nichtich/Catmandu-Importer-getJSON/issues
  homepage: https://github.com/nichtich/Catmandu-Importer-getJSON
  repository: https://github.com/nichtich/Catmandu-Importer-getJSON.git
version: 0.40
