---
abstract: 'load JSON-encoded data from a server using a GET HTTP request'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  Module::Build::Tiny: 0.038
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Importer-getJSON
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: 0.9
  Furl: 3.0
  Moo: 1.0
  URI::Template: 0.18
  perl: v5.10.1
resources:
  bugtracker: https://github.com/nichtich/Catmandu-Importer-getJSON/issues
  homepage: https://github.com/nichtich/Catmandu-Importer-getJSON
  repository: https://github.com/nichtich/Catmandu-Importer-getJSON.git
version: 0.41
x_contributors:
  - 'Jakob Voss <voss@gbv.de>'
  - 'vpeil <vitali.peil@uni-bielefeld.de>'
